name: feature check
on:
  push:
    branches:
    - 'staging'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      env:
        TOKEN: ${{ token.JENKTOKEN }}
      - run: curl -I http://ec2-34-227-221-111.compute-1.amazonaws.com:8080/job/git%20test/build?token=1234 --user remotetriger:"$TOKEN"